### PR TITLE
buildfarm badges

### PR DESCRIPTION
**Pull request by davetcoleman**
@wjwwood could you point me to an easy example/rostool for parsing a directory for all package names so this doesn't have to be hard coded?

also, given you understanding of the buildfarm am I using a good representative set to monitor the health of moveit in the buildfarm? e.g. 64bit and platform?

the generated example is here https://github.com/ros-planning/moveit

### CODE REVIEW

**Comment by wjwwood** [comment]
I think you can just call one of these functions: https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/packages.py#L71

The returned structure is something like `{path_to_package_xml: package_obj, ...}`.

**Comment by davetcoleman** [comment]
`catkin list -u` does the trick, except it only works within a catkin workspace even though its help file says it can work in any directory. Does that bug sound right to you?

> Lists catkin packages in the workspace or other arbitray folders.

**Comment by wjwwood** [comment]
That sounds like a bug, but you should ask @jbohren whether or not that's intended behavior. There might be a reason it behaves like that. I don't know.

**Comment by davetcoleman** [comment]
I'm going to merge this because this script makes the nice markdown table.

However I gave up on using `catkin list` and am instead switched to a python script that creates html

http://discourse.ros.org/t/moveit-package-tracking-via-table/415

**Pull request merged**
